/*
InsightOps REST API

### Overview  Our REST API lets you use InsightOps through HTTP requests. Currently, the REST API allows you to perform the majority of the actions available through the UI, and has some additional functionality that is not available through the UI. You may use this API to automate common tasks (for example, via shell scripts), and to generally interact with InsightOps programmatically.  This page precisely describes the REST API and serves as a reference for the API. Each HTTP method and each URL endpoint is documented in a self-contained unit so that users only need to read about the HTTP methods relevant to them.  ### Terminology  * A **log entry** is an individual log event. * A **log** is a collection of log entries, or a single log stream. * A **log set** is a logical-only collection of logs, i.e. logs can be in multiple logsets and deleting a logset only deletes the relation between logs, not the logs themselves. * [Log Entry Query Language](https://docs.rapid7.com/insightops/log-search) (**LEQL**) is the query language used in Insight Ops to search log data.

API version: latest
Contact: support@rapid7.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package insightops

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the TargetResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TargetResponse{}

// TargetResponse struct for TargetResponse
type TargetResponse struct {
	// The id of the notification target.
	Id string `json:"id"`
	// The name of the notification target.
	Name string `json:"name"`
	// The description of the notification target.
	Description string                  `json:"description"`
	Type        NotificationTypeEnum    `json:"type"`
	ParamsSet   TargetResponseParamsSet `json:"params_set"`
	// A list of key-value pairs that may indicate some auxiliary information about the notification target.
	UserData        map[string]interface{} `json:"user_data"`
	AlertContentSet TargetAlertContentSet  `json:"alert_content_set"`
}

type _TargetResponse TargetResponse

// NewTargetResponse instantiates a new TargetResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTargetResponse(id string, name string, description string, type_ NotificationTypeEnum, paramsSet TargetResponseParamsSet, userData map[string]interface{}, alertContentSet TargetAlertContentSet) *TargetResponse {
	this := TargetResponse{}
	this.Id = id
	this.Name = name
	this.Description = description
	this.Type = type_
	this.ParamsSet = paramsSet
	this.UserData = userData
	this.AlertContentSet = alertContentSet
	return &this
}

// NewTargetResponseWithDefaults instantiates a new TargetResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTargetResponseWithDefaults() *TargetResponse {
	this := TargetResponse{}
	return &this
}

// GetId returns the Id field value
func (o *TargetResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *TargetResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *TargetResponse) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *TargetResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *TargetResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *TargetResponse) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value
func (o *TargetResponse) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *TargetResponse) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *TargetResponse) SetDescription(v string) {
	o.Description = v
}

// GetType returns the Type field value
func (o *TargetResponse) GetType() NotificationTypeEnum {
	if o == nil {
		var ret NotificationTypeEnum
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *TargetResponse) GetTypeOk() (*NotificationTypeEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *TargetResponse) SetType(v NotificationTypeEnum) {
	o.Type = v
}

// GetParamsSet returns the ParamsSet field value
func (o *TargetResponse) GetParamsSet() TargetResponseParamsSet {
	if o == nil {
		var ret TargetResponseParamsSet
		return ret
	}

	return o.ParamsSet
}

// GetParamsSetOk returns a tuple with the ParamsSet field value
// and a boolean to check if the value has been set.
func (o *TargetResponse) GetParamsSetOk() (*TargetResponseParamsSet, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ParamsSet, true
}

// SetParamsSet sets field value
func (o *TargetResponse) SetParamsSet(v TargetResponseParamsSet) {
	o.ParamsSet = v
}

// GetUserData returns the UserData field value
func (o *TargetResponse) GetUserData() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.UserData
}

// GetUserDataOk returns a tuple with the UserData field value
// and a boolean to check if the value has been set.
func (o *TargetResponse) GetUserDataOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.UserData, true
}

// SetUserData sets field value
func (o *TargetResponse) SetUserData(v map[string]interface{}) {
	o.UserData = v
}

// GetAlertContentSet returns the AlertContentSet field value
func (o *TargetResponse) GetAlertContentSet() TargetAlertContentSet {
	if o == nil {
		var ret TargetAlertContentSet
		return ret
	}

	return o.AlertContentSet
}

// GetAlertContentSetOk returns a tuple with the AlertContentSet field value
// and a boolean to check if the value has been set.
func (o *TargetResponse) GetAlertContentSetOk() (*TargetAlertContentSet, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AlertContentSet, true
}

// SetAlertContentSet sets field value
func (o *TargetResponse) SetAlertContentSet(v TargetAlertContentSet) {
	o.AlertContentSet = v
}

func (o TargetResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TargetResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["description"] = o.Description
	toSerialize["type"] = o.Type
	toSerialize["params_set"] = o.ParamsSet
	toSerialize["user_data"] = o.UserData
	toSerialize["alert_content_set"] = o.AlertContentSet
	return toSerialize, nil
}

func (o *TargetResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"description",
		"type",
		"params_set",
		"user_data",
		"alert_content_set",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTargetResponse := _TargetResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTargetResponse)

	if err != nil {
		return err
	}

	*o = TargetResponse(varTargetResponse)

	return err
}

type NullableTargetResponse struct {
	value *TargetResponse
	isSet bool
}

func (v NullableTargetResponse) Get() *TargetResponse {
	return v.value
}

func (v *NullableTargetResponse) Set(val *TargetResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTargetResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTargetResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTargetResponse(val *TargetResponse) *NullableTargetResponse {
	return &NullableTargetResponse{value: val, isSet: true}
}

func (v NullableTargetResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTargetResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
