/*
InsightOps REST API

### Overview  Our REST API lets you use InsightOps through HTTP requests. Currently, the REST API allows you to perform the majority of the actions available through the UI, and has some additional functionality that is not available through the UI. You may use this API to automate common tasks (for example, via shell scripts), and to generally interact with InsightOps programmatically.  This page precisely describes the REST API and serves as a reference for the API. Each HTTP method and each URL endpoint is documented in a self-contained unit so that users only need to read about the HTTP methods relevant to them.  ### Terminology  * A **log entry** is an individual log event. * A **log** is a collection of log entries, or a single log stream. * A **log set** is a logical-only collection of logs, i.e. logs can be in multiple logsets and deleting a logset only deletes the relation between logs, not the logs themselves. * [Log Entry Query Language](https://docs.rapid7.com/insightops/log-search) (**LEQL**) is the query language used in Insight Ops to search log data.

API version: latest
Contact: support@rapid7.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package insightops

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the InactivityLeql type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InactivityLeql{}

// InactivityLeql The [LEQL](https://docs.rapid7.com/insightidr/log-search/#write-a-leql-query) query used by this inactivity detection rule to identify matching log entries. Notifications will be triggered when no matches have been identified for the amount of time configured for this detection rule.
type InactivityLeql struct {
	// The `where()` clause of the [LEQL](https://docs.rapid7.com/insightidr/log-search/#write-a-leql-query) query, for example, `where(foo)`. If empty, the detection rule matches all log entries.
	Statement string `json:"statement"`
}

type _InactivityLeql InactivityLeql

// NewInactivityLeql instantiates a new InactivityLeql object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInactivityLeql(statement string) *InactivityLeql {
	this := InactivityLeql{}
	this.Statement = statement
	return &this
}

// NewInactivityLeqlWithDefaults instantiates a new InactivityLeql object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInactivityLeqlWithDefaults() *InactivityLeql {
	this := InactivityLeql{}
	return &this
}

// GetStatement returns the Statement field value
func (o *InactivityLeql) GetStatement() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Statement
}

// GetStatementOk returns a tuple with the Statement field value
// and a boolean to check if the value has been set.
func (o *InactivityLeql) GetStatementOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Statement, true
}

// SetStatement sets field value
func (o *InactivityLeql) SetStatement(v string) {
	o.Statement = v
}

func (o InactivityLeql) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InactivityLeql) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["statement"] = o.Statement
	return toSerialize, nil
}

func (o *InactivityLeql) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"statement",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInactivityLeql := _InactivityLeql{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInactivityLeql)

	if err != nil {
		return err
	}

	*o = InactivityLeql(varInactivityLeql)

	return err
}

type NullableInactivityLeql struct {
	value *InactivityLeql
	isSet bool
}

func (v NullableInactivityLeql) Get() *InactivityLeql {
	return v.value
}

func (v *NullableInactivityLeql) Set(val *InactivityLeql) {
	v.value = val
	v.isSet = true
}

func (v NullableInactivityLeql) IsSet() bool {
	return v.isSet
}

func (v *NullableInactivityLeql) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInactivityLeql(val *InactivityLeql) *NullableInactivityLeql {
	return &NullableInactivityLeql{value: val, isSet: true}
}

func (v NullableInactivityLeql) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInactivityLeql) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
