/*
InsightOps REST API

### Overview  Our REST API lets you use InsightOps through HTTP requests. Currently, the REST API allows you to perform the majority of the actions available through the UI, and has some additional functionality that is not available through the UI. You may use this API to automate common tasks (for example, via shell scripts), and to generally interact with InsightOps programmatically.  This page precisely describes the REST API and serves as a reference for the API. Each HTTP method and each URL endpoint is documented in a self-contained unit so that users only need to read about the HTTP methods relevant to them.  ### Terminology  * A **log entry** is an individual log event. * A **log** is a collection of log entries, or a single log stream. * A **log set** is a logical-only collection of logs, i.e. logs can be in multiple logsets and deleting a logset only deletes the relation between logs, not the logs themselves. * [Log Entry Query Language](https://docs.rapid7.com/insightops/log-search) (**LEQL**) is the query language used in Insight Ops to search log data.

API version: latest
Contact: support@rapid7.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package insightops

import (
	"encoding/json"
)

// checks if the MetricsInputLogsetsByNameMetric type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MetricsInputLogsetsByNameMetric{}

// MetricsInputLogsetsByNameMetric struct for MetricsInputLogsetsByNameMetric
type MetricsInputLogsetsByNameMetric struct {
	// The name of the pre-computed query.
	Name *string `json:"name,omitempty"`
	// The description of the pre-computed query.
	Description *string `json:"description,omitempty"`
	// This indicates whether the pre-computed query is enabled or not.
	Enabled interface{}                             `json:"enabled,omitempty"`
	Logsets *MetricsInputLogsetsByNameMetricLogsets `json:"logsets,omitempty"`
	Leql    *LeqlMetrics                            `json:"leql,omitempty"`
	// The time window in seconds, that each PCQ datapoint corresponds to.
	Resolution *int32 `json:"resolution,omitempty"`
	// The length of time in seconds, that the PCQ will be stored for.
	Retention *int32 `json:"retention,omitempty"`
}

// NewMetricsInputLogsetsByNameMetric instantiates a new MetricsInputLogsetsByNameMetric object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMetricsInputLogsetsByNameMetric() *MetricsInputLogsetsByNameMetric {
	this := MetricsInputLogsetsByNameMetric{}
	return &this
}

// NewMetricsInputLogsetsByNameMetricWithDefaults instantiates a new MetricsInputLogsetsByNameMetric object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMetricsInputLogsetsByNameMetricWithDefaults() *MetricsInputLogsetsByNameMetric {
	this := MetricsInputLogsetsByNameMetric{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *MetricsInputLogsetsByNameMetric) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricsInputLogsetsByNameMetric) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *MetricsInputLogsetsByNameMetric) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *MetricsInputLogsetsByNameMetric) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *MetricsInputLogsetsByNameMetric) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricsInputLogsetsByNameMetric) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *MetricsInputLogsetsByNameMetric) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *MetricsInputLogsetsByNameMetric) SetDescription(v string) {
	o.Description = &v
}

// GetEnabled returns the Enabled field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MetricsInputLogsetsByNameMetric) GetEnabled() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MetricsInputLogsetsByNameMetric) GetEnabledOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return &o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *MetricsInputLogsetsByNameMetric) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given interface{} and assigns it to the Enabled field.
func (o *MetricsInputLogsetsByNameMetric) SetEnabled(v interface{}) {
	o.Enabled = v
}

// GetLogsets returns the Logsets field value if set, zero value otherwise.
func (o *MetricsInputLogsetsByNameMetric) GetLogsets() MetricsInputLogsetsByNameMetricLogsets {
	if o == nil || IsNil(o.Logsets) {
		var ret MetricsInputLogsetsByNameMetricLogsets
		return ret
	}
	return *o.Logsets
}

// GetLogsetsOk returns a tuple with the Logsets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricsInputLogsetsByNameMetric) GetLogsetsOk() (*MetricsInputLogsetsByNameMetricLogsets, bool) {
	if o == nil || IsNil(o.Logsets) {
		return nil, false
	}
	return o.Logsets, true
}

// HasLogsets returns a boolean if a field has been set.
func (o *MetricsInputLogsetsByNameMetric) HasLogsets() bool {
	if o != nil && !IsNil(o.Logsets) {
		return true
	}

	return false
}

// SetLogsets gets a reference to the given MetricsInputLogsetsByNameMetricLogsets and assigns it to the Logsets field.
func (o *MetricsInputLogsetsByNameMetric) SetLogsets(v MetricsInputLogsetsByNameMetricLogsets) {
	o.Logsets = &v
}

// GetLeql returns the Leql field value if set, zero value otherwise.
func (o *MetricsInputLogsetsByNameMetric) GetLeql() LeqlMetrics {
	if o == nil || IsNil(o.Leql) {
		var ret LeqlMetrics
		return ret
	}
	return *o.Leql
}

// GetLeqlOk returns a tuple with the Leql field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricsInputLogsetsByNameMetric) GetLeqlOk() (*LeqlMetrics, bool) {
	if o == nil || IsNil(o.Leql) {
		return nil, false
	}
	return o.Leql, true
}

// HasLeql returns a boolean if a field has been set.
func (o *MetricsInputLogsetsByNameMetric) HasLeql() bool {
	if o != nil && !IsNil(o.Leql) {
		return true
	}

	return false
}

// SetLeql gets a reference to the given LeqlMetrics and assigns it to the Leql field.
func (o *MetricsInputLogsetsByNameMetric) SetLeql(v LeqlMetrics) {
	o.Leql = &v
}

// GetResolution returns the Resolution field value if set, zero value otherwise.
func (o *MetricsInputLogsetsByNameMetric) GetResolution() int32 {
	if o == nil || IsNil(o.Resolution) {
		var ret int32
		return ret
	}
	return *o.Resolution
}

// GetResolutionOk returns a tuple with the Resolution field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricsInputLogsetsByNameMetric) GetResolutionOk() (*int32, bool) {
	if o == nil || IsNil(o.Resolution) {
		return nil, false
	}
	return o.Resolution, true
}

// HasResolution returns a boolean if a field has been set.
func (o *MetricsInputLogsetsByNameMetric) HasResolution() bool {
	if o != nil && !IsNil(o.Resolution) {
		return true
	}

	return false
}

// SetResolution gets a reference to the given int32 and assigns it to the Resolution field.
func (o *MetricsInputLogsetsByNameMetric) SetResolution(v int32) {
	o.Resolution = &v
}

// GetRetention returns the Retention field value if set, zero value otherwise.
func (o *MetricsInputLogsetsByNameMetric) GetRetention() int32 {
	if o == nil || IsNil(o.Retention) {
		var ret int32
		return ret
	}
	return *o.Retention
}

// GetRetentionOk returns a tuple with the Retention field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricsInputLogsetsByNameMetric) GetRetentionOk() (*int32, bool) {
	if o == nil || IsNil(o.Retention) {
		return nil, false
	}
	return o.Retention, true
}

// HasRetention returns a boolean if a field has been set.
func (o *MetricsInputLogsetsByNameMetric) HasRetention() bool {
	if o != nil && !IsNil(o.Retention) {
		return true
	}

	return false
}

// SetRetention gets a reference to the given int32 and assigns it to the Retention field.
func (o *MetricsInputLogsetsByNameMetric) SetRetention(v int32) {
	o.Retention = &v
}

func (o MetricsInputLogsetsByNameMetric) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MetricsInputLogsetsByNameMetric) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if o.Enabled != nil {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.Logsets) {
		toSerialize["logsets"] = o.Logsets
	}
	if !IsNil(o.Leql) {
		toSerialize["leql"] = o.Leql
	}
	if !IsNil(o.Resolution) {
		toSerialize["resolution"] = o.Resolution
	}
	if !IsNil(o.Retention) {
		toSerialize["retention"] = o.Retention
	}
	return toSerialize, nil
}

type NullableMetricsInputLogsetsByNameMetric struct {
	value *MetricsInputLogsetsByNameMetric
	isSet bool
}

func (v NullableMetricsInputLogsetsByNameMetric) Get() *MetricsInputLogsetsByNameMetric {
	return v.value
}

func (v *NullableMetricsInputLogsetsByNameMetric) Set(val *MetricsInputLogsetsByNameMetric) {
	v.value = val
	v.isSet = true
}

func (v NullableMetricsInputLogsetsByNameMetric) IsSet() bool {
	return v.isSet
}

func (v *NullableMetricsInputLogsetsByNameMetric) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMetricsInputLogsetsByNameMetric(val *MetricsInputLogsetsByNameMetric) *NullableMetricsInputLogsetsByNameMetric {
	return &NullableMetricsInputLogsetsByNameMetric{value: val, isSet: true}
}

func (v NullableMetricsInputLogsetsByNameMetric) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMetricsInputLogsetsByNameMetric) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
