/*
InsightOps REST API

### Overview  Our REST API lets you use InsightOps through HTTP requests. Currently, the REST API allows you to perform the majority of the actions available through the UI, and has some additional functionality that is not available through the UI. You may use this API to automate common tasks (for example, via shell scripts), and to generally interact with InsightOps programmatically.  This page precisely describes the REST API and serves as a reference for the API. Each HTTP method and each URL endpoint is documented in a self-contained unit so that users only need to read about the HTTP methods relevant to them.  ### Terminology  * A **log entry** is an individual log event. * A **log** is a collection of log entries, or a single log stream. * A **log set** is a logical-only collection of logs, i.e. logs can be in multiple logsets and deleting a logset only deletes the relation between logs, not the logs themselves. * [Log Entry Query Language](https://docs.rapid7.com/insightops/log-search) (**LEQL**) is the query language used in Insight Ops to search log data.

API version: latest
Contact: support@rapid7.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package insightops

import (
	"encoding/json"
)

// checks if the PatchBasicTag type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PatchBasicTag{}

// PatchBasicTag struct for PatchBasicTag
type PatchBasicTag struct {
	Tag *PatchBasicTagTag `json:"tag,omitempty"`
}

// NewPatchBasicTag instantiates a new PatchBasicTag object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchBasicTag() *PatchBasicTag {
	this := PatchBasicTag{}
	return &this
}

// NewPatchBasicTagWithDefaults instantiates a new PatchBasicTag object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchBasicTagWithDefaults() *PatchBasicTag {
	this := PatchBasicTag{}
	return &this
}

// GetTag returns the Tag field value if set, zero value otherwise.
func (o *PatchBasicTag) GetTag() PatchBasicTagTag {
	if o == nil || IsNil(o.Tag) {
		var ret PatchBasicTagTag
		return ret
	}
	return *o.Tag
}

// GetTagOk returns a tuple with the Tag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchBasicTag) GetTagOk() (*PatchBasicTagTag, bool) {
	if o == nil || IsNil(o.Tag) {
		return nil, false
	}
	return o.Tag, true
}

// HasTag returns a boolean if a field has been set.
func (o *PatchBasicTag) HasTag() bool {
	if o != nil && !IsNil(o.Tag) {
		return true
	}

	return false
}

// SetTag gets a reference to the given PatchBasicTagTag and assigns it to the Tag field.
func (o *PatchBasicTag) SetTag(v PatchBasicTagTag) {
	o.Tag = &v
}

func (o PatchBasicTag) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PatchBasicTag) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Tag) {
		toSerialize["tag"] = o.Tag
	}
	return toSerialize, nil
}

type NullablePatchBasicTag struct {
	value *PatchBasicTag
	isSet bool
}

func (v NullablePatchBasicTag) Get() *PatchBasicTag {
	return v.value
}

func (v *NullablePatchBasicTag) Set(val *PatchBasicTag) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchBasicTag) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchBasicTag) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchBasicTag(val *PatchBasicTag) *NullablePatchBasicTag {
	return &NullablePatchBasicTag{value: val, isSet: true}
}

func (v NullablePatchBasicTag) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchBasicTag) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
