/*
InsightOps REST API

### Overview  Our REST API lets you use InsightOps through HTTP requests. Currently, the REST API allows you to perform the majority of the actions available through the UI, and has some additional functionality that is not available through the UI. You may use this API to automate common tasks (for example, via shell scripts), and to generally interact with InsightOps programmatically.  This page precisely describes the REST API and serves as a reference for the API. Each HTTP method and each URL endpoint is documented in a self-contained unit so that users only need to read about the HTTP methods relevant to them.  ### Terminology  * A **log entry** is an individual log event. * A **log** is a collection of log entries, or a single log stream. * A **log set** is a logical-only collection of logs, i.e. logs can be in multiple logsets and deleting a logset only deletes the relation between logs, not the logs themselves. * [Log Entry Query Language](https://docs.rapid7.com/insightops/log-search) (**LEQL**) is the query language used in Insight Ops to search log data.

API version: latest
Contact: support@rapid7.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package insightops

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreateTagAction type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateTagAction{}

// CreateTagAction struct for CreateTagAction
type CreateTagAction struct {
	// \\ When set to true, the notification is enabled. When set to false, the notification is disabled.
	Enabled bool `json:"enabled"`
	// The number of log entries that the pattern detection rule needs to match for a notification to be triggered (within a window of time, controlled by the `min_matches_period` parameter).
	MinMatchesCount int32 `json:"min_matches_count"`
	// The time window used in combination with the `min_matches_count` parameter to determine if enough log entries have matched a pattern detection rule for an alert notification to be sent. For example, if `min_matches_count=2`, and `min_matches_period=\"5Minute\"`, then this notification will be triggered whenever two log entries match the pattern detection rule within 5 minutes.
	MinMatchesPeriod string `json:"min_matches_period"`
	// The maximum number of notifications that will be triggered within a window of time, controlled by the `min_report_period` parameter.
	MinReportCount  int32      `json:"min_report_count"`
	MinReportPeriod PeriodEnum `json:"min_report_period"`
	// The list of notification targets for this notification.
	Targets []CreateTagTarget `json:"targets"`
	// Always set to \"Alert\".
	Type *string `json:"type,omitempty"`
}

type _CreateTagAction CreateTagAction

// NewCreateTagAction instantiates a new CreateTagAction object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateTagAction(enabled bool, minMatchesCount int32, minMatchesPeriod string, minReportCount int32, minReportPeriod PeriodEnum, targets []CreateTagTarget) *CreateTagAction {
	this := CreateTagAction{}
	this.Enabled = enabled
	this.MinMatchesCount = minMatchesCount
	this.MinMatchesPeriod = minMatchesPeriod
	this.MinReportCount = minReportCount
	this.MinReportPeriod = minReportPeriod
	this.Targets = targets
	return &this
}

// NewCreateTagActionWithDefaults instantiates a new CreateTagAction object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateTagActionWithDefaults() *CreateTagAction {
	this := CreateTagAction{}
	var minMatchesCount int32 = 0
	this.MinMatchesCount = minMatchesCount
	var minReportCount int32 = 1
	this.MinReportCount = minReportCount
	var minReportPeriod PeriodEnum = PeriodEnum(HOUR)
	this.MinReportPeriod = minReportPeriod
	return &this
}

// GetEnabled returns the Enabled field value
func (o *CreateTagAction) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *CreateTagAction) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *CreateTagAction) SetEnabled(v bool) {
	o.Enabled = v
}

// GetMinMatchesCount returns the MinMatchesCount field value
func (o *CreateTagAction) GetMinMatchesCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MinMatchesCount
}

// GetMinMatchesCountOk returns a tuple with the MinMatchesCount field value
// and a boolean to check if the value has been set.
func (o *CreateTagAction) GetMinMatchesCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MinMatchesCount, true
}

// SetMinMatchesCount sets field value
func (o *CreateTagAction) SetMinMatchesCount(v int32) {
	o.MinMatchesCount = v
}

// GetMinMatchesPeriod returns the MinMatchesPeriod field value
func (o *CreateTagAction) GetMinMatchesPeriod() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MinMatchesPeriod
}

// GetMinMatchesPeriodOk returns a tuple with the MinMatchesPeriod field value
// and a boolean to check if the value has been set.
func (o *CreateTagAction) GetMinMatchesPeriodOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MinMatchesPeriod, true
}

// SetMinMatchesPeriod sets field value
func (o *CreateTagAction) SetMinMatchesPeriod(v string) {
	o.MinMatchesPeriod = v
}

// GetMinReportCount returns the MinReportCount field value
func (o *CreateTagAction) GetMinReportCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MinReportCount
}

// GetMinReportCountOk returns a tuple with the MinReportCount field value
// and a boolean to check if the value has been set.
func (o *CreateTagAction) GetMinReportCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MinReportCount, true
}

// SetMinReportCount sets field value
func (o *CreateTagAction) SetMinReportCount(v int32) {
	o.MinReportCount = v
}

// GetMinReportPeriod returns the MinReportPeriod field value
func (o *CreateTagAction) GetMinReportPeriod() PeriodEnum {
	if o == nil {
		var ret PeriodEnum
		return ret
	}

	return o.MinReportPeriod
}

// GetMinReportPeriodOk returns a tuple with the MinReportPeriod field value
// and a boolean to check if the value has been set.
func (o *CreateTagAction) GetMinReportPeriodOk() (*PeriodEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MinReportPeriod, true
}

// SetMinReportPeriod sets field value
func (o *CreateTagAction) SetMinReportPeriod(v PeriodEnum) {
	o.MinReportPeriod = v
}

// GetTargets returns the Targets field value
func (o *CreateTagAction) GetTargets() []CreateTagTarget {
	if o == nil {
		var ret []CreateTagTarget
		return ret
	}

	return o.Targets
}

// GetTargetsOk returns a tuple with the Targets field value
// and a boolean to check if the value has been set.
func (o *CreateTagAction) GetTargetsOk() ([]CreateTagTarget, bool) {
	if o == nil {
		return nil, false
	}
	return o.Targets, true
}

// SetTargets sets field value
func (o *CreateTagAction) SetTargets(v []CreateTagTarget) {
	o.Targets = v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *CreateTagAction) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTagAction) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *CreateTagAction) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *CreateTagAction) SetType(v string) {
	o.Type = &v
}

func (o CreateTagAction) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateTagAction) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["enabled"] = o.Enabled
	toSerialize["min_matches_count"] = o.MinMatchesCount
	toSerialize["min_matches_period"] = o.MinMatchesPeriod
	toSerialize["min_report_count"] = o.MinReportCount
	toSerialize["min_report_period"] = o.MinReportPeriod
	toSerialize["targets"] = o.Targets
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

func (o *CreateTagAction) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"enabled",
		"min_matches_count",
		"min_matches_period",
		"min_report_count",
		"min_report_period",
		"targets",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateTagAction := _CreateTagAction{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateTagAction)

	if err != nil {
		return err
	}

	*o = CreateTagAction(varCreateTagAction)

	return err
}

type NullableCreateTagAction struct {
	value *CreateTagAction
	isSet bool
}

func (v NullableCreateTagAction) Get() *CreateTagAction {
	return v.value
}

func (v *NullableCreateTagAction) Set(val *CreateTagAction) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateTagAction) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateTagAction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateTagAction(val *CreateTagAction) *NullableCreateTagAction {
	return &NullableCreateTagAction{value: val, isSet: true}
}

func (v NullableCreateTagAction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateTagAction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
