/*
InsightOps REST API

### Overview  Our REST API lets you use InsightOps through HTTP requests. Currently, the REST API allows you to perform the majority of the actions available through the UI, and has some additional functionality that is not available through the UI. You may use this API to automate common tasks (for example, via shell scripts), and to generally interact with InsightOps programmatically.  This page precisely describes the REST API and serves as a reference for the API. Each HTTP method and each URL endpoint is documented in a self-contained unit so that users only need to read about the HTTP methods relevant to them.  ### Terminology  * A **log entry** is an individual log event. * A **log** is a collection of log entries, or a single log stream. * A **log set** is a logical-only collection of logs, i.e. logs can be in multiple logsets and deleting a logset only deletes the relation between logs, not the logs themselves. * [Log Entry Query Language](https://docs.rapid7.com/insightops/log-search) (**LEQL**) is the query language used in Insight Ops to search log data.

API version: latest
Contact: support@rapid7.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package insightops

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the PutTagAnomalyAlertTag type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PutTagAnomalyAlertTag{}

// PutTagAnomalyAlertTag struct for PutTagAnomalyAlertTag
type PutTagAnomalyAlertTag struct {
	// The name of the detection rule.
	Name string `json:"name"`
	// The IDs of the logs that the detection rule operates on.
	Sources []SourcesIdArrayInner `json:"sources"`
	// Always set to \"AlertNotify\".
	Type string `json:"type"`
	// Always set to \"AnomalyAlert\".
	SubType string `json:"sub_type"`
	// The description of the detection rule.
	Description *string `json:"description,omitempty"`
	// The notifications attached to the detection rule.
	Actions []CreateTagActionAnomaly `json:"actions,omitempty"`
	// A list of key-value pairs that may indicate some auxiliary information about the change detection rule.
	UserData map[string]interface{} `json:"user_data,omitempty"`
	// ID of the scheduled query associated with this change detection rule.
	ScheduledQueryId *string                `json:"scheduled_query_id,omitempty"`
	ScheduledQuery   ScheduledQueryResponse `json:"scheduled_query"`
	// The percentage that defines when to trigger notifications. The percentage can be positive or negative. For example, if the percentage is set to -50, then notifications will be triggered when the query result for the time range defined by the `time_value` and `time_period` parameters is 50% smaller when compared to the same query over the time range defined by the `timeframe_value` and `timeframe_period` parameters.
	ThresholdValue int32 `json:"threshold_value"`
	// This ensures investigations are ordered by priority in Investigation Management. Must be >=0
	Priority *int32 `json:"priority,omitempty"`
}

type _PutTagAnomalyAlertTag PutTagAnomalyAlertTag

// NewPutTagAnomalyAlertTag instantiates a new PutTagAnomalyAlertTag object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPutTagAnomalyAlertTag(name string, sources []SourcesIdArrayInner, type_ string, subType string, scheduledQuery ScheduledQueryResponse, thresholdValue int32) *PutTagAnomalyAlertTag {
	this := PutTagAnomalyAlertTag{}
	this.Name = name
	this.Sources = sources
	this.Type = type_
	this.SubType = subType
	this.ScheduledQuery = scheduledQuery
	this.ThresholdValue = thresholdValue
	return &this
}

// NewPutTagAnomalyAlertTagWithDefaults instantiates a new PutTagAnomalyAlertTag object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPutTagAnomalyAlertTagWithDefaults() *PutTagAnomalyAlertTag {
	this := PutTagAnomalyAlertTag{}
	return &this
}

// GetName returns the Name field value
func (o *PutTagAnomalyAlertTag) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *PutTagAnomalyAlertTag) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *PutTagAnomalyAlertTag) SetName(v string) {
	o.Name = v
}

// GetSources returns the Sources field value
func (o *PutTagAnomalyAlertTag) GetSources() []SourcesIdArrayInner {
	if o == nil {
		var ret []SourcesIdArrayInner
		return ret
	}

	return o.Sources
}

// GetSourcesOk returns a tuple with the Sources field value
// and a boolean to check if the value has been set.
func (o *PutTagAnomalyAlertTag) GetSourcesOk() ([]SourcesIdArrayInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Sources, true
}

// SetSources sets field value
func (o *PutTagAnomalyAlertTag) SetSources(v []SourcesIdArrayInner) {
	o.Sources = v
}

// GetType returns the Type field value
func (o *PutTagAnomalyAlertTag) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *PutTagAnomalyAlertTag) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *PutTagAnomalyAlertTag) SetType(v string) {
	o.Type = v
}

// GetSubType returns the SubType field value
func (o *PutTagAnomalyAlertTag) GetSubType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SubType
}

// GetSubTypeOk returns a tuple with the SubType field value
// and a boolean to check if the value has been set.
func (o *PutTagAnomalyAlertTag) GetSubTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SubType, true
}

// SetSubType sets field value
func (o *PutTagAnomalyAlertTag) SetSubType(v string) {
	o.SubType = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *PutTagAnomalyAlertTag) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PutTagAnomalyAlertTag) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *PutTagAnomalyAlertTag) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *PutTagAnomalyAlertTag) SetDescription(v string) {
	o.Description = &v
}

// GetActions returns the Actions field value if set, zero value otherwise.
func (o *PutTagAnomalyAlertTag) GetActions() []CreateTagActionAnomaly {
	if o == nil || IsNil(o.Actions) {
		var ret []CreateTagActionAnomaly
		return ret
	}
	return o.Actions
}

// GetActionsOk returns a tuple with the Actions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PutTagAnomalyAlertTag) GetActionsOk() ([]CreateTagActionAnomaly, bool) {
	if o == nil || IsNil(o.Actions) {
		return nil, false
	}
	return o.Actions, true
}

// HasActions returns a boolean if a field has been set.
func (o *PutTagAnomalyAlertTag) HasActions() bool {
	if o != nil && !IsNil(o.Actions) {
		return true
	}

	return false
}

// SetActions gets a reference to the given []CreateTagActionAnomaly and assigns it to the Actions field.
func (o *PutTagAnomalyAlertTag) SetActions(v []CreateTagActionAnomaly) {
	o.Actions = v
}

// GetUserData returns the UserData field value if set, zero value otherwise.
func (o *PutTagAnomalyAlertTag) GetUserData() map[string]interface{} {
	if o == nil || IsNil(o.UserData) {
		var ret map[string]interface{}
		return ret
	}
	return o.UserData
}

// GetUserDataOk returns a tuple with the UserData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PutTagAnomalyAlertTag) GetUserDataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.UserData) {
		return map[string]interface{}{}, false
	}
	return o.UserData, true
}

// HasUserData returns a boolean if a field has been set.
func (o *PutTagAnomalyAlertTag) HasUserData() bool {
	if o != nil && !IsNil(o.UserData) {
		return true
	}

	return false
}

// SetUserData gets a reference to the given map[string]interface{} and assigns it to the UserData field.
func (o *PutTagAnomalyAlertTag) SetUserData(v map[string]interface{}) {
	o.UserData = v
}

// GetScheduledQueryId returns the ScheduledQueryId field value if set, zero value otherwise.
func (o *PutTagAnomalyAlertTag) GetScheduledQueryId() string {
	if o == nil || IsNil(o.ScheduledQueryId) {
		var ret string
		return ret
	}
	return *o.ScheduledQueryId
}

// GetScheduledQueryIdOk returns a tuple with the ScheduledQueryId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PutTagAnomalyAlertTag) GetScheduledQueryIdOk() (*string, bool) {
	if o == nil || IsNil(o.ScheduledQueryId) {
		return nil, false
	}
	return o.ScheduledQueryId, true
}

// HasScheduledQueryId returns a boolean if a field has been set.
func (o *PutTagAnomalyAlertTag) HasScheduledQueryId() bool {
	if o != nil && !IsNil(o.ScheduledQueryId) {
		return true
	}

	return false
}

// SetScheduledQueryId gets a reference to the given string and assigns it to the ScheduledQueryId field.
func (o *PutTagAnomalyAlertTag) SetScheduledQueryId(v string) {
	o.ScheduledQueryId = &v
}

// GetScheduledQuery returns the ScheduledQuery field value
func (o *PutTagAnomalyAlertTag) GetScheduledQuery() ScheduledQueryResponse {
	if o == nil {
		var ret ScheduledQueryResponse
		return ret
	}

	return o.ScheduledQuery
}

// GetScheduledQueryOk returns a tuple with the ScheduledQuery field value
// and a boolean to check if the value has been set.
func (o *PutTagAnomalyAlertTag) GetScheduledQueryOk() (*ScheduledQueryResponse, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ScheduledQuery, true
}

// SetScheduledQuery sets field value
func (o *PutTagAnomalyAlertTag) SetScheduledQuery(v ScheduledQueryResponse) {
	o.ScheduledQuery = v
}

// GetThresholdValue returns the ThresholdValue field value
func (o *PutTagAnomalyAlertTag) GetThresholdValue() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ThresholdValue
}

// GetThresholdValueOk returns a tuple with the ThresholdValue field value
// and a boolean to check if the value has been set.
func (o *PutTagAnomalyAlertTag) GetThresholdValueOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ThresholdValue, true
}

// SetThresholdValue sets field value
func (o *PutTagAnomalyAlertTag) SetThresholdValue(v int32) {
	o.ThresholdValue = v
}

// GetPriority returns the Priority field value if set, zero value otherwise.
func (o *PutTagAnomalyAlertTag) GetPriority() int32 {
	if o == nil || IsNil(o.Priority) {
		var ret int32
		return ret
	}
	return *o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PutTagAnomalyAlertTag) GetPriorityOk() (*int32, bool) {
	if o == nil || IsNil(o.Priority) {
		return nil, false
	}
	return o.Priority, true
}

// HasPriority returns a boolean if a field has been set.
func (o *PutTagAnomalyAlertTag) HasPriority() bool {
	if o != nil && !IsNil(o.Priority) {
		return true
	}

	return false
}

// SetPriority gets a reference to the given int32 and assigns it to the Priority field.
func (o *PutTagAnomalyAlertTag) SetPriority(v int32) {
	o.Priority = &v
}

func (o PutTagAnomalyAlertTag) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PutTagAnomalyAlertTag) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["sources"] = o.Sources
	toSerialize["type"] = o.Type
	toSerialize["sub_type"] = o.SubType
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Actions) {
		toSerialize["actions"] = o.Actions
	}
	if !IsNil(o.UserData) {
		toSerialize["user_data"] = o.UserData
	}
	if !IsNil(o.ScheduledQueryId) {
		toSerialize["scheduled_query_id"] = o.ScheduledQueryId
	}
	toSerialize["scheduled_query"] = o.ScheduledQuery
	toSerialize["threshold_value"] = o.ThresholdValue
	if !IsNil(o.Priority) {
		toSerialize["priority"] = o.Priority
	}
	return toSerialize, nil
}

func (o *PutTagAnomalyAlertTag) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"sources",
		"type",
		"sub_type",
		"scheduled_query",
		"threshold_value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPutTagAnomalyAlertTag := _PutTagAnomalyAlertTag{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPutTagAnomalyAlertTag)

	if err != nil {
		return err
	}

	*o = PutTagAnomalyAlertTag(varPutTagAnomalyAlertTag)

	return err
}

type NullablePutTagAnomalyAlertTag struct {
	value *PutTagAnomalyAlertTag
	isSet bool
}

func (v NullablePutTagAnomalyAlertTag) Get() *PutTagAnomalyAlertTag {
	return v.value
}

func (v *NullablePutTagAnomalyAlertTag) Set(val *PutTagAnomalyAlertTag) {
	v.value = val
	v.isSet = true
}

func (v NullablePutTagAnomalyAlertTag) IsSet() bool {
	return v.isSet
}

func (v *NullablePutTagAnomalyAlertTag) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePutTagAnomalyAlertTag(val *PutTagAnomalyAlertTag) *NullablePutTagAnomalyAlertTag {
	return &NullablePutTagAnomalyAlertTag{value: val, isSet: true}
}

func (v NullablePutTagAnomalyAlertTag) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePutTagAnomalyAlertTag) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
