/*
InsightOps REST API

### Overview  Our REST API lets you use InsightOps through HTTP requests. Currently, the REST API allows you to perform the majority of the actions available through the UI, and has some additional functionality that is not available through the UI. You may use this API to automate common tasks (for example, via shell scripts), and to generally interact with InsightOps programmatically.  This page precisely describes the REST API and serves as a reference for the API. Each HTTP method and each URL endpoint is documented in a self-contained unit so that users only need to read about the HTTP methods relevant to them.  ### Terminology  * A **log entry** is an individual log event. * A **log** is a collection of log entries, or a single log stream. * A **log set** is a logical-only collection of logs, i.e. logs can be in multiple logsets and deleting a logset only deletes the relation between logs, not the logs themselves. * [Log Entry Query Language](https://docs.rapid7.com/insightops/log-search) (**LEQL**) is the query language used in Insight Ops to search log data.

API version: latest
Contact: support@rapid7.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package insightops

import (
	"encoding/json"
)

// checks if the PatchSavedQuerySavedQuery type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PatchSavedQuerySavedQuery{}

// PatchSavedQuerySavedQuery struct for PatchSavedQuerySavedQuery
type PatchSavedQuerySavedQuery struct {
	// The name for the Saved Query (doesn't need to be unique).
	Name *string    `json:"name,omitempty"`
	Leql *LeqlPATCH `json:"leql,omitempty"`
	// The log keys of the logs which the query is run against.
	Logs []string `json:"logs,omitempty"`
}

// NewPatchSavedQuerySavedQuery instantiates a new PatchSavedQuerySavedQuery object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchSavedQuerySavedQuery() *PatchSavedQuerySavedQuery {
	this := PatchSavedQuerySavedQuery{}
	return &this
}

// NewPatchSavedQuerySavedQueryWithDefaults instantiates a new PatchSavedQuerySavedQuery object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchSavedQuerySavedQueryWithDefaults() *PatchSavedQuerySavedQuery {
	this := PatchSavedQuerySavedQuery{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *PatchSavedQuerySavedQuery) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchSavedQuerySavedQuery) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *PatchSavedQuerySavedQuery) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *PatchSavedQuerySavedQuery) SetName(v string) {
	o.Name = &v
}

// GetLeql returns the Leql field value if set, zero value otherwise.
func (o *PatchSavedQuerySavedQuery) GetLeql() LeqlPATCH {
	if o == nil || IsNil(o.Leql) {
		var ret LeqlPATCH
		return ret
	}
	return *o.Leql
}

// GetLeqlOk returns a tuple with the Leql field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchSavedQuerySavedQuery) GetLeqlOk() (*LeqlPATCH, bool) {
	if o == nil || IsNil(o.Leql) {
		return nil, false
	}
	return o.Leql, true
}

// HasLeql returns a boolean if a field has been set.
func (o *PatchSavedQuerySavedQuery) HasLeql() bool {
	if o != nil && !IsNil(o.Leql) {
		return true
	}

	return false
}

// SetLeql gets a reference to the given LeqlPATCH and assigns it to the Leql field.
func (o *PatchSavedQuerySavedQuery) SetLeql(v LeqlPATCH) {
	o.Leql = &v
}

// GetLogs returns the Logs field value if set, zero value otherwise.
func (o *PatchSavedQuerySavedQuery) GetLogs() []string {
	if o == nil || IsNil(o.Logs) {
		var ret []string
		return ret
	}
	return o.Logs
}

// GetLogsOk returns a tuple with the Logs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchSavedQuerySavedQuery) GetLogsOk() ([]string, bool) {
	if o == nil || IsNil(o.Logs) {
		return nil, false
	}
	return o.Logs, true
}

// HasLogs returns a boolean if a field has been set.
func (o *PatchSavedQuerySavedQuery) HasLogs() bool {
	if o != nil && !IsNil(o.Logs) {
		return true
	}

	return false
}

// SetLogs gets a reference to the given []string and assigns it to the Logs field.
func (o *PatchSavedQuerySavedQuery) SetLogs(v []string) {
	o.Logs = v
}

func (o PatchSavedQuerySavedQuery) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PatchSavedQuerySavedQuery) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Leql) {
		toSerialize["leql"] = o.Leql
	}
	if !IsNil(o.Logs) {
		toSerialize["logs"] = o.Logs
	}
	return toSerialize, nil
}

type NullablePatchSavedQuerySavedQuery struct {
	value *PatchSavedQuerySavedQuery
	isSet bool
}

func (v NullablePatchSavedQuerySavedQuery) Get() *PatchSavedQuerySavedQuery {
	return v.value
}

func (v *NullablePatchSavedQuerySavedQuery) Set(val *PatchSavedQuerySavedQuery) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchSavedQuerySavedQuery) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchSavedQuerySavedQuery) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchSavedQuerySavedQuery(val *PatchSavedQuerySavedQuery) *NullablePatchSavedQuerySavedQuery {
	return &NullablePatchSavedQuerySavedQuery{value: val, isSet: true}
}

func (v NullablePatchSavedQuerySavedQuery) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchSavedQuerySavedQuery) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
