/*
InsightOps REST API

### Overview  Our REST API lets you use InsightOps through HTTP requests. Currently, the REST API allows you to perform the majority of the actions available through the UI, and has some additional functionality that is not available through the UI. You may use this API to automate common tasks (for example, via shell scripts), and to generally interact with InsightOps programmatically.  This page precisely describes the REST API and serves as a reference for the API. Each HTTP method and each URL endpoint is documented in a self-contained unit so that users only need to read about the HTTP methods relevant to them.  ### Terminology  * A **log entry** is an individual log event. * A **log** is a collection of log entries, or a single log stream. * A **log set** is a logical-only collection of logs, i.e. logs can be in multiple logsets and deleting a logset only deletes the relation between logs, not the logs themselves. * [Log Entry Query Language](https://docs.rapid7.com/insightops/log-search) (**LEQL**) is the query language used in Insight Ops to search log data.

API version: latest
Contact: support@rapid7.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package insightops

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// PatchManagementTagByIdRequestTag - struct for PatchManagementTagByIdRequestTag
type PatchManagementTagByIdRequestTag struct {
	PatchBasicTag               *PatchBasicTag
	PatchTagWithAnomalyAlert    *PatchTagWithAnomalyAlert
	PatchTagWithInactivityAlert *PatchTagWithInactivityAlert
}

// PatchBasicTagAsPatchManagementTagByIdRequestTag is a convenience function that returns PatchBasicTag wrapped in PatchManagementTagByIdRequestTag
func PatchBasicTagAsPatchManagementTagByIdRequestTag(v *PatchBasicTag) PatchManagementTagByIdRequestTag {
	return PatchManagementTagByIdRequestTag{
		PatchBasicTag: v,
	}
}

// PatchTagWithAnomalyAlertAsPatchManagementTagByIdRequestTag is a convenience function that returns PatchTagWithAnomalyAlert wrapped in PatchManagementTagByIdRequestTag
func PatchTagWithAnomalyAlertAsPatchManagementTagByIdRequestTag(v *PatchTagWithAnomalyAlert) PatchManagementTagByIdRequestTag {
	return PatchManagementTagByIdRequestTag{
		PatchTagWithAnomalyAlert: v,
	}
}

// PatchTagWithInactivityAlertAsPatchManagementTagByIdRequestTag is a convenience function that returns PatchTagWithInactivityAlert wrapped in PatchManagementTagByIdRequestTag
func PatchTagWithInactivityAlertAsPatchManagementTagByIdRequestTag(v *PatchTagWithInactivityAlert) PatchManagementTagByIdRequestTag {
	return PatchManagementTagByIdRequestTag{
		PatchTagWithInactivityAlert: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *PatchManagementTagByIdRequestTag) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into PatchBasicTag
	err = newStrictDecoder(data).Decode(&dst.PatchBasicTag)
	if err == nil {
		jsonPatchBasicTag, _ := json.Marshal(dst.PatchBasicTag)
		if string(jsonPatchBasicTag) == "{}" { // empty struct
			dst.PatchBasicTag = nil
		} else {
			if err = validator.Validate(dst.PatchBasicTag); err != nil {
				dst.PatchBasicTag = nil
			} else {
				match++
			}
		}
	} else {
		dst.PatchBasicTag = nil
	}

	// try to unmarshal data into PatchTagWithAnomalyAlert
	err = newStrictDecoder(data).Decode(&dst.PatchTagWithAnomalyAlert)
	if err == nil {
		jsonPatchTagWithAnomalyAlert, _ := json.Marshal(dst.PatchTagWithAnomalyAlert)
		if string(jsonPatchTagWithAnomalyAlert) == "{}" { // empty struct
			dst.PatchTagWithAnomalyAlert = nil
		} else {
			if err = validator.Validate(dst.PatchTagWithAnomalyAlert); err != nil {
				dst.PatchTagWithAnomalyAlert = nil
			} else {
				match++
			}
		}
	} else {
		dst.PatchTagWithAnomalyAlert = nil
	}

	// try to unmarshal data into PatchTagWithInactivityAlert
	err = newStrictDecoder(data).Decode(&dst.PatchTagWithInactivityAlert)
	if err == nil {
		jsonPatchTagWithInactivityAlert, _ := json.Marshal(dst.PatchTagWithInactivityAlert)
		if string(jsonPatchTagWithInactivityAlert) == "{}" { // empty struct
			dst.PatchTagWithInactivityAlert = nil
		} else {
			if err = validator.Validate(dst.PatchTagWithInactivityAlert); err != nil {
				dst.PatchTagWithInactivityAlert = nil
			} else {
				match++
			}
		}
	} else {
		dst.PatchTagWithInactivityAlert = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.PatchBasicTag = nil
		dst.PatchTagWithAnomalyAlert = nil
		dst.PatchTagWithInactivityAlert = nil

		return fmt.Errorf("data matches more than one schema in oneOf(PatchManagementTagByIdRequestTag)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(PatchManagementTagByIdRequestTag)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src PatchManagementTagByIdRequestTag) MarshalJSON() ([]byte, error) {
	if src.PatchBasicTag != nil {
		return json.Marshal(&src.PatchBasicTag)
	}

	if src.PatchTagWithAnomalyAlert != nil {
		return json.Marshal(&src.PatchTagWithAnomalyAlert)
	}

	if src.PatchTagWithInactivityAlert != nil {
		return json.Marshal(&src.PatchTagWithInactivityAlert)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *PatchManagementTagByIdRequestTag) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.PatchBasicTag != nil {
		return obj.PatchBasicTag
	}

	if obj.PatchTagWithAnomalyAlert != nil {
		return obj.PatchTagWithAnomalyAlert
	}

	if obj.PatchTagWithInactivityAlert != nil {
		return obj.PatchTagWithInactivityAlert
	}

	// all schemas are nil
	return nil
}

type NullablePatchManagementTagByIdRequestTag struct {
	value *PatchManagementTagByIdRequestTag
	isSet bool
}

func (v NullablePatchManagementTagByIdRequestTag) Get() *PatchManagementTagByIdRequestTag {
	return v.value
}

func (v *NullablePatchManagementTagByIdRequestTag) Set(val *PatchManagementTagByIdRequestTag) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchManagementTagByIdRequestTag) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchManagementTagByIdRequestTag) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchManagementTagByIdRequestTag(val *PatchManagementTagByIdRequestTag) *NullablePatchManagementTagByIdRequestTag {
	return &NullablePatchManagementTagByIdRequestTag{value: val, isSet: true}
}

func (v NullablePatchManagementTagByIdRequestTag) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchManagementTagByIdRequestTag) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
