/*
InsightOps REST API

### Overview  Our REST API lets you use InsightOps through HTTP requests. Currently, the REST API allows you to perform the majority of the actions available through the UI, and has some additional functionality that is not available through the UI. You may use this API to automate common tasks (for example, via shell scripts), and to generally interact with InsightOps programmatically.  This page precisely describes the REST API and serves as a reference for the API. Each HTTP method and each URL endpoint is documented in a self-contained unit so that users only need to read about the HTTP methods relevant to them.  ### Terminology  * A **log entry** is an individual log event. * A **log** is a collection of log entries, or a single log stream. * A **log set** is a logical-only collection of logs, i.e. logs can be in multiple logsets and deleting a logset only deletes the relation between logs, not the logs themselves. * [Log Entry Query Language](https://docs.rapid7.com/insightops/log-search) (**LEQL**) is the query language used in Insight Ops to search log data.

API version: latest
Contact: support@rapid7.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package insightops

import (
	"encoding/json"
)

// checks if the CreateVariableRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateVariableRequest{}

// CreateVariableRequest struct for CreateVariableRequest
type CreateVariableRequest struct {
	Variable *LeqlVariableRequest `json:"variable,omitempty"`
}

// NewCreateVariableRequest instantiates a new CreateVariableRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateVariableRequest() *CreateVariableRequest {
	this := CreateVariableRequest{}
	return &this
}

// NewCreateVariableRequestWithDefaults instantiates a new CreateVariableRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateVariableRequestWithDefaults() *CreateVariableRequest {
	this := CreateVariableRequest{}
	return &this
}

// GetVariable returns the Variable field value if set, zero value otherwise.
func (o *CreateVariableRequest) GetVariable() LeqlVariableRequest {
	if o == nil || IsNil(o.Variable) {
		var ret LeqlVariableRequest
		return ret
	}
	return *o.Variable
}

// GetVariableOk returns a tuple with the Variable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVariableRequest) GetVariableOk() (*LeqlVariableRequest, bool) {
	if o == nil || IsNil(o.Variable) {
		return nil, false
	}
	return o.Variable, true
}

// HasVariable returns a boolean if a field has been set.
func (o *CreateVariableRequest) HasVariable() bool {
	if o != nil && !IsNil(o.Variable) {
		return true
	}

	return false
}

// SetVariable gets a reference to the given LeqlVariableRequest and assigns it to the Variable field.
func (o *CreateVariableRequest) SetVariable(v LeqlVariableRequest) {
	o.Variable = &v
}

func (o CreateVariableRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateVariableRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Variable) {
		toSerialize["variable"] = o.Variable
	}
	return toSerialize, nil
}

type NullableCreateVariableRequest struct {
	value *CreateVariableRequest
	isSet bool
}

func (v NullableCreateVariableRequest) Get() *CreateVariableRequest {
	return v.value
}

func (v *NullableCreateVariableRequest) Set(val *CreateVariableRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateVariableRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateVariableRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateVariableRequest(val *CreateVariableRequest) *NullableCreateVariableRequest {
	return &NullableCreateVariableRequest{value: val, isSet: true}
}

func (v NullableCreateVariableRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateVariableRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
