/*
InsightOps REST API

### Overview  Our REST API lets you use InsightOps through HTTP requests. Currently, the REST API allows you to perform the majority of the actions available through the UI, and has some additional functionality that is not available through the UI. You may use this API to automate common tasks (for example, via shell scripts), and to generally interact with InsightOps programmatically.  This page precisely describes the REST API and serves as a reference for the API. Each HTTP method and each URL endpoint is documented in a self-contained unit so that users only need to read about the HTTP methods relevant to them.  ### Terminology  * A **log entry** is an individual log event. * A **log** is a collection of log entries, or a single log stream. * A **log set** is a logical-only collection of logs, i.e. logs can be in multiple logsets and deleting a logset only deletes the relation between logs, not the logs themselves. * [Log Entry Query Language](https://docs.rapid7.com/insightops/log-search) (**LEQL**) is the query language used in Insight Ops to search log data.

API version: latest
Contact: support@rapid7.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package insightops

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ExportJobLinksInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExportJobLinksInner{}

// ExportJobLinksInner struct for ExportJobLinksInner
type ExportJobLinksInner struct {
	Rel  string `json:"rel"`
	Href string `json:"href"`
}

type _ExportJobLinksInner ExportJobLinksInner

// NewExportJobLinksInner instantiates a new ExportJobLinksInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExportJobLinksInner(rel string, href string) *ExportJobLinksInner {
	this := ExportJobLinksInner{}
	this.Rel = rel
	this.Href = href
	return &this
}

// NewExportJobLinksInnerWithDefaults instantiates a new ExportJobLinksInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExportJobLinksInnerWithDefaults() *ExportJobLinksInner {
	this := ExportJobLinksInner{}
	return &this
}

// GetRel returns the Rel field value
func (o *ExportJobLinksInner) GetRel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Rel
}

// GetRelOk returns a tuple with the Rel field value
// and a boolean to check if the value has been set.
func (o *ExportJobLinksInner) GetRelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Rel, true
}

// SetRel sets field value
func (o *ExportJobLinksInner) SetRel(v string) {
	o.Rel = v
}

// GetHref returns the Href field value
func (o *ExportJobLinksInner) GetHref() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Href
}

// GetHrefOk returns a tuple with the Href field value
// and a boolean to check if the value has been set.
func (o *ExportJobLinksInner) GetHrefOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Href, true
}

// SetHref sets field value
func (o *ExportJobLinksInner) SetHref(v string) {
	o.Href = v
}

func (o ExportJobLinksInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExportJobLinksInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["rel"] = o.Rel
	toSerialize["href"] = o.Href
	return toSerialize, nil
}

func (o *ExportJobLinksInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"rel",
		"href",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varExportJobLinksInner := _ExportJobLinksInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varExportJobLinksInner)

	if err != nil {
		return err
	}

	*o = ExportJobLinksInner(varExportJobLinksInner)

	return err
}

type NullableExportJobLinksInner struct {
	value *ExportJobLinksInner
	isSet bool
}

func (v NullableExportJobLinksInner) Get() *ExportJobLinksInner {
	return v.value
}

func (v *NullableExportJobLinksInner) Set(val *ExportJobLinksInner) {
	v.value = val
	v.isSet = true
}

func (v NullableExportJobLinksInner) IsSet() bool {
	return v.isSet
}

func (v *NullableExportJobLinksInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExportJobLinksInner(val *ExportJobLinksInner) *NullableExportJobLinksInner {
	return &NullableExportJobLinksInner{value: val, isSet: true}
}

func (v NullableExportJobLinksInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExportJobLinksInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
