/*
InsightOps REST API

### Overview  Our REST API lets you use InsightOps through HTTP requests. Currently, the REST API allows you to perform the majority of the actions available through the UI, and has some additional functionality that is not available through the UI. You may use this API to automate common tasks (for example, via shell scripts), and to generally interact with InsightOps programmatically.  This page precisely describes the REST API and serves as a reference for the API. Each HTTP method and each URL endpoint is documented in a self-contained unit so that users only need to read about the HTTP methods relevant to them.  ### Terminology  * A **log entry** is an individual log event. * A **log** is a collection of log entries, or a single log stream. * A **log set** is a logical-only collection of logs, i.e. logs can be in multiple logsets and deleting a logset only deletes the relation between logs, not the logs themselves. * [Log Entry Query Language](https://docs.rapid7.com/insightops/log-search) (**LEQL**) is the query language used in Insight Ops to search log data.

API version: latest
Contact: support@rapid7.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package insightops

import (
	"encoding/json"
)

// checks if the CreatePutTarget type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreatePutTarget{}

// CreatePutTarget struct for CreatePutTarget
type CreatePutTarget struct {
	Target *CreatePutTargetTarget `json:"target,omitempty"`
}

// NewCreatePutTarget instantiates a new CreatePutTarget object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreatePutTarget() *CreatePutTarget {
	this := CreatePutTarget{}
	return &this
}

// NewCreatePutTargetWithDefaults instantiates a new CreatePutTarget object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreatePutTargetWithDefaults() *CreatePutTarget {
	this := CreatePutTarget{}
	return &this
}

// GetTarget returns the Target field value if set, zero value otherwise.
func (o *CreatePutTarget) GetTarget() CreatePutTargetTarget {
	if o == nil || IsNil(o.Target) {
		var ret CreatePutTargetTarget
		return ret
	}
	return *o.Target
}

// GetTargetOk returns a tuple with the Target field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePutTarget) GetTargetOk() (*CreatePutTargetTarget, bool) {
	if o == nil || IsNil(o.Target) {
		return nil, false
	}
	return o.Target, true
}

// HasTarget returns a boolean if a field has been set.
func (o *CreatePutTarget) HasTarget() bool {
	if o != nil && !IsNil(o.Target) {
		return true
	}

	return false
}

// SetTarget gets a reference to the given CreatePutTargetTarget and assigns it to the Target field.
func (o *CreatePutTarget) SetTarget(v CreatePutTargetTarget) {
	o.Target = &v
}

func (o CreatePutTarget) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreatePutTarget) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Target) {
		toSerialize["target"] = o.Target
	}
	return toSerialize, nil
}

type NullableCreatePutTarget struct {
	value *CreatePutTarget
	isSet bool
}

func (v NullableCreatePutTarget) Get() *CreatePutTarget {
	return v.value
}

func (v *NullableCreatePutTarget) Set(val *CreatePutTarget) {
	v.value = val
	v.isSet = true
}

func (v NullableCreatePutTarget) IsSet() bool {
	return v.isSet
}

func (v *NullableCreatePutTarget) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreatePutTarget(val *CreatePutTarget) *NullableCreatePutTarget {
	return &NullableCreatePutTarget{value: val, isSet: true}
}

func (v NullableCreatePutTarget) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreatePutTarget) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
