/*
InsightOps REST API

### Overview  Our REST API lets you use InsightOps through HTTP requests. Currently, the REST API allows you to perform the majority of the actions available through the UI, and has some additional functionality that is not available through the UI. You may use this API to automate common tasks (for example, via shell scripts), and to generally interact with InsightOps programmatically.  This page precisely describes the REST API and serves as a reference for the API. Each HTTP method and each URL endpoint is documented in a self-contained unit so that users only need to read about the HTTP methods relevant to them.  ### Terminology  * A **log entry** is an individual log event. * A **log** is a collection of log entries, or a single log stream. * A **log set** is a logical-only collection of logs, i.e. logs can be in multiple logsets and deleting a logset only deletes the relation between logs, not the logs themselves. * [Log Entry Query Language](https://docs.rapid7.com/insightops/log-search) (**LEQL**) is the query language used in Insight Ops to search log data.

API version: latest
Contact: support@rapid7.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package insightops

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the KvpInfoInnerValue type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KvpInfoInnerValue{}

// KvpInfoInnerValue struct for KvpInfoInnerValue
type KvpInfoInnerValue struct {
	// the data associated with the key.
	Text string `json:"text"`
	// the position in the log entry of the first character of the value (first character in the log entry is at position 0).
	Start int32 `json:"start"`
	// the position in the log entry of the next character after the last character of the value.
	End int32 `json:"end"`
}

type _KvpInfoInnerValue KvpInfoInnerValue

// NewKvpInfoInnerValue instantiates a new KvpInfoInnerValue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKvpInfoInnerValue(text string, start int32, end int32) *KvpInfoInnerValue {
	this := KvpInfoInnerValue{}
	this.Text = text
	this.Start = start
	this.End = end
	return &this
}

// NewKvpInfoInnerValueWithDefaults instantiates a new KvpInfoInnerValue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKvpInfoInnerValueWithDefaults() *KvpInfoInnerValue {
	this := KvpInfoInnerValue{}
	return &this
}

// GetText returns the Text field value
func (o *KvpInfoInnerValue) GetText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Text
}

// GetTextOk returns a tuple with the Text field value
// and a boolean to check if the value has been set.
func (o *KvpInfoInnerValue) GetTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Text, true
}

// SetText sets field value
func (o *KvpInfoInnerValue) SetText(v string) {
	o.Text = v
}

// GetStart returns the Start field value
func (o *KvpInfoInnerValue) GetStart() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Start
}

// GetStartOk returns a tuple with the Start field value
// and a boolean to check if the value has been set.
func (o *KvpInfoInnerValue) GetStartOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Start, true
}

// SetStart sets field value
func (o *KvpInfoInnerValue) SetStart(v int32) {
	o.Start = v
}

// GetEnd returns the End field value
func (o *KvpInfoInnerValue) GetEnd() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.End
}

// GetEndOk returns a tuple with the End field value
// and a boolean to check if the value has been set.
func (o *KvpInfoInnerValue) GetEndOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.End, true
}

// SetEnd sets field value
func (o *KvpInfoInnerValue) SetEnd(v int32) {
	o.End = v
}

func (o KvpInfoInnerValue) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KvpInfoInnerValue) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["text"] = o.Text
	toSerialize["start"] = o.Start
	toSerialize["end"] = o.End
	return toSerialize, nil
}

func (o *KvpInfoInnerValue) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"text",
		"start",
		"end",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varKvpInfoInnerValue := _KvpInfoInnerValue{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varKvpInfoInnerValue)

	if err != nil {
		return err
	}

	*o = KvpInfoInnerValue(varKvpInfoInnerValue)

	return err
}

type NullableKvpInfoInnerValue struct {
	value *KvpInfoInnerValue
	isSet bool
}

func (v NullableKvpInfoInnerValue) Get() *KvpInfoInnerValue {
	return v.value
}

func (v *NullableKvpInfoInnerValue) Set(val *KvpInfoInnerValue) {
	v.value = val
	v.isSet = true
}

func (v NullableKvpInfoInnerValue) IsSet() bool {
	return v.isSet
}

func (v *NullableKvpInfoInnerValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKvpInfoInnerValue(val *KvpInfoInnerValue) *NullableKvpInfoInnerValue {
	return &NullableKvpInfoInnerValue{value: val, isSet: true}
}

func (v NullableKvpInfoInnerValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKvpInfoInnerValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
