/*
InsightOps REST API

### Overview  Our REST API lets you use InsightOps through HTTP requests. Currently, the REST API allows you to perform the majority of the actions available through the UI, and has some additional functionality that is not available through the UI. You may use this API to automate common tasks (for example, via shell scripts), and to generally interact with InsightOps programmatically.  This page precisely describes the REST API and serves as a reference for the API. Each HTTP method and each URL endpoint is documented in a self-contained unit so that users only need to read about the HTTP methods relevant to them.  ### Terminology  * A **log entry** is an individual log event. * A **log** is a collection of log entries, or a single log stream. * A **log set** is a logical-only collection of logs, i.e. logs can be in multiple logsets and deleting a logset only deletes the relation between logs, not the logs themselves. * [Log Entry Query Language](https://docs.rapid7.com/insightops/log-search) (**LEQL**) is the query language used in Insight Ops to search log data.

API version: latest
Contact: support@rapid7.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package insightops

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// PollQuery200Response - struct for PollQuery200Response
type PollQuery200Response struct {
	EventsContinuation      *EventsContinuation
	EventsResponse          *EventsResponse
	StatisticalContinuation *StatisticalContinuation
	StatisticalResponse     *StatisticalResponse
}

// EventsContinuationAsPollQuery200Response is a convenience function that returns EventsContinuation wrapped in PollQuery200Response
func EventsContinuationAsPollQuery200Response(v *EventsContinuation) PollQuery200Response {
	return PollQuery200Response{
		EventsContinuation: v,
	}
}

// EventsResponseAsPollQuery200Response is a convenience function that returns EventsResponse wrapped in PollQuery200Response
func EventsResponseAsPollQuery200Response(v *EventsResponse) PollQuery200Response {
	return PollQuery200Response{
		EventsResponse: v,
	}
}

// StatisticalContinuationAsPollQuery200Response is a convenience function that returns StatisticalContinuation wrapped in PollQuery200Response
func StatisticalContinuationAsPollQuery200Response(v *StatisticalContinuation) PollQuery200Response {
	return PollQuery200Response{
		StatisticalContinuation: v,
	}
}

// StatisticalResponseAsPollQuery200Response is a convenience function that returns StatisticalResponse wrapped in PollQuery200Response
func StatisticalResponseAsPollQuery200Response(v *StatisticalResponse) PollQuery200Response {
	return PollQuery200Response{
		StatisticalResponse: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *PollQuery200Response) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into EventsContinuation
	err = newStrictDecoder(data).Decode(&dst.EventsContinuation)
	if err == nil {
		jsonEventsContinuation, _ := json.Marshal(dst.EventsContinuation)
		if string(jsonEventsContinuation) == "{}" { // empty struct
			dst.EventsContinuation = nil
		} else {
			if err = validator.Validate(dst.EventsContinuation); err != nil {
				dst.EventsContinuation = nil
			} else {
				match++
			}
		}
	} else {
		dst.EventsContinuation = nil
	}

	// try to unmarshal data into EventsResponse
	err = newStrictDecoder(data).Decode(&dst.EventsResponse)
	if err == nil {
		jsonEventsResponse, _ := json.Marshal(dst.EventsResponse)
		if string(jsonEventsResponse) == "{}" { // empty struct
			dst.EventsResponse = nil
		} else {
			if err = validator.Validate(dst.EventsResponse); err != nil {
				dst.EventsResponse = nil
			} else {
				match++
			}
		}
	} else {
		dst.EventsResponse = nil
	}

	// try to unmarshal data into StatisticalContinuation
	err = newStrictDecoder(data).Decode(&dst.StatisticalContinuation)
	if err == nil {
		jsonStatisticalContinuation, _ := json.Marshal(dst.StatisticalContinuation)
		if string(jsonStatisticalContinuation) == "{}" { // empty struct
			dst.StatisticalContinuation = nil
		} else {
			if err = validator.Validate(dst.StatisticalContinuation); err != nil {
				dst.StatisticalContinuation = nil
			} else {
				match++
			}
		}
	} else {
		dst.StatisticalContinuation = nil
	}

	// try to unmarshal data into StatisticalResponse
	err = newStrictDecoder(data).Decode(&dst.StatisticalResponse)
	if err == nil {
		jsonStatisticalResponse, _ := json.Marshal(dst.StatisticalResponse)
		if string(jsonStatisticalResponse) == "{}" { // empty struct
			dst.StatisticalResponse = nil
		} else {
			if err = validator.Validate(dst.StatisticalResponse); err != nil {
				dst.StatisticalResponse = nil
			} else {
				match++
			}
		}
	} else {
		dst.StatisticalResponse = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.EventsContinuation = nil
		dst.EventsResponse = nil
		dst.StatisticalContinuation = nil
		dst.StatisticalResponse = nil

		return fmt.Errorf("data matches more than one schema in oneOf(PollQuery200Response)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(PollQuery200Response)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src PollQuery200Response) MarshalJSON() ([]byte, error) {
	if src.EventsContinuation != nil {
		return json.Marshal(&src.EventsContinuation)
	}

	if src.EventsResponse != nil {
		return json.Marshal(&src.EventsResponse)
	}

	if src.StatisticalContinuation != nil {
		return json.Marshal(&src.StatisticalContinuation)
	}

	if src.StatisticalResponse != nil {
		return json.Marshal(&src.StatisticalResponse)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *PollQuery200Response) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.EventsContinuation != nil {
		return obj.EventsContinuation
	}

	if obj.EventsResponse != nil {
		return obj.EventsResponse
	}

	if obj.StatisticalContinuation != nil {
		return obj.StatisticalContinuation
	}

	if obj.StatisticalResponse != nil {
		return obj.StatisticalResponse
	}

	// all schemas are nil
	return nil
}

type NullablePollQuery200Response struct {
	value *PollQuery200Response
	isSet bool
}

func (v NullablePollQuery200Response) Get() *PollQuery200Response {
	return v.value
}

func (v *NullablePollQuery200Response) Set(val *PollQuery200Response) {
	v.value = val
	v.isSet = true
}

func (v NullablePollQuery200Response) IsSet() bool {
	return v.isSet
}

func (v *NullablePollQuery200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePollQuery200Response(val *PollQuery200Response) *NullablePollQuery200Response {
	return &NullablePollQuery200Response{value: val, isSet: true}
}

func (v NullablePollQuery200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePollQuery200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
